### ISSUE TITLE
Not detect tabs with size 4

### ISSUE THREAD

**Issue by aspeddro** [NMAC427/guess-indent.nvim#2]
Thanks for this plugin.

`guess-indent` not detect tabs with size 4.

Example using lua file.

https://user-images.githubusercontent.com/16160544/156821866-a6ab4acf-b4ca-407e-8a8c-2779497907bb.mp4

**Comment by NMAC427** [comment]
Hi!
This is actually the expected behaviour (when using tabs, guess-indent only sets the `expandtab` option to false).
Guess-indent only looks at the content of the current buffer, and there is no way to calculate or infer how wide a tab should be rendered (because in the end a tab is just a single `\t` character). That's why it is up to the user to set the value of `tabstop` themselves it they are using tabs.
